# Generated by Django 5.2.17 on 2026-08-28 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_key', models.CharField(db_index=True, max_length=120)),
                ('source', models.CharField(max_length=16)),
                ('reference_date', models.DateField()),
                ('value', models.DecimalField(decimal_places=8, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['series_key', 'reference_date'],
                'indexes': [models.Index(fields=['series_key', 'reference_date'], name='core_market_series__6a8f3e_idx')],
                'constraints': [models.UniqueConstraint(fields=('series_key', 'reference_date'), name='uniq_series_point')],
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dlp_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
